### ISSUE TITLE
Feature Request: Add support for RSS in header and/or footer

### ISSUE THREAD

**Issue by girisreenivas** [TryGhost/Edition#14]
Love the theme - would like to see a link in the header and/or footer for RSS for visitors to add the feed to the RSS reader of their choice. I understand Ghost has native RSS support at /rss off any page.

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
