### ISSUE TITLE
ES6 (I think?) issue

### ISSUE THREAD

**Issue by greenhamsam** [TryGhost/Edition#16]
Hi team! Please bear with me, I'm a n00b web developer. Apologies if this belongs on StackOverflow rather than here.

I've made some tiny changes to the Edition theme (I'm attempting to add search functionality), but I'm running into some errors.

My setup:
- Node v.14.16.0
- Yarn 1.22.4
- Ghost-CLI 1.16.3
- Gulp CLI version 2.3.0
- Gulp local version 4.0.2

Initially, I forked and cloned the Edition repo into the ghost/content/themes folder. 
I then tried cloning a new version outside of my ghost folder to see if it works there, but no dice.

## What I did:
I'm trying to run 'yarn dev' or 'yarn zip'.

I ran 'ghost start'. This ran fine.

I cd'd into the edition directory and ran 'yarn install'. No issues.

Then I ran 'yarn dev' and got this output:
```
yarn run v1.22.4
warning edition@1.0.0: The engine "ghost" appears to be invalid.
warning edition@1.0.0: The engine "ghost-api" appears to be invalid.
$ gulp
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/sambeckbessinger/Code/ghost/content/themes/edition/node_modules/beeper/index.js
require() of ES modules is not supported.
require() of /Users/sambeckbessinger/Code/ghost/content/themes/edition/node_modules/beeper/index.js from /Users/sambeckbessinger/Code/ghost/content/themes/edition/gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/sambeckbessinger/Code/ghost/content/themes/edition/node_modules/beeper/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/sambeckbessinger/Code/ghost/content/themes/edition/gulpfile.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I get the same output when running `yarn zip`.

I tried adding "type": "module", to the package.json file. Running `yarn zip` then gives me a "require is not defined" reference error.

I suspect I have a dependency problem, or something else in my environment isn't right. Any ideas what I can do to get this working?

Thanks so much for your help!

**Comment by minimaluminium** [comment]
Hey @greenhamsam, thanks for your detailed feedback. This issue was fixed in https://github.com/TryGhost/Edition/commit/da29dbe0e52cfb3824b428d1077076c9fa0c3000. Update your repo to the latest version, install the dependencies again, and all should be good :)

**Comment by greenhamsam** [comment]
Thank you!
