### ISSUE TITLE
CLS on desktop version for posts

### ISSUE THREAD

**Issue by louisnt-prod** [TryGhost/Edition#17]
## Problem

I've noticed a layout shift on posts pages due to the height of the images missing.

## To reproduce

Lighthouse > Desktop > Generate Report

**Results:**
- Amazing performances on all other metrics
- Cumulative Layout Shift: **0.255**

In the profiling section, we can notice that this layout shift is due to the cover image that has no height

## Suggested solution

This would be amazing to add height to images in the template to prevent this layout shift and provide the best experience ever to our users.

Thank you!

**Comment by louisnt-prod** [comment]
The featured image on a single post template
`div class="single-media kg-width-wide"` > `img sizes="(min-width: 1023px) 920px, calc(90vw)"`

I feel that it must be linked to image responsiveness, any idea of a workaround? I don't mind editing the template on my side to improve this, but I'm not very familiar with Ghost theme.

**Comment by minimaluminium** [comment]
What I have in mind is maybe you could use `min-height` to make the layout shifting as minimal as possible. For example, a bit of CSS which you can use as a code injection.

```html
<style>
    .single-media {
        min-height: 500px;
    }
</style>
```

This isn't a very good solution though, works only if your site featured images are consistent in terms of aspect ratio. Also should consider smaller screens.
