### ISSUE TITLE
Releases seem to have been overlooked.

### ISSUE THREAD

**Issue by scott91e1** [TryGhost/Edition#18]
Hello,

Many thanks for creating this entire ecosystem BTW 🐱‍👤

I am looking to finesse the footer for a hosted site using the Edition template.  My plan is/was to find the repo and begin plugging away.  Unfortunately the README mentions downloading from https://github.com/TryGhost/Edition/releases but no releases exist for the project...

Perhaps a minor oversight?

Regards,

Scott.

**Comment by minimaluminium** [comment]
Hey @scott91e1, thanks for the feedback. We don't do releases for themes except Casper for simplicity, and I agree it was misleading on Edition's README pointing to releases which are nowhere to be found. I've just updated the link :)

**Comment by scott91e1** [comment]
That's OK.  Me being a newbie to the ghost/node world, if I wanted to have a more complex footer than the standard template, what would be best course of action?  I am a coder, just not from the JavaScript world.  Thanks.

**Comment by minimaluminium** [comment]
For Edition theme, the footer can be customized in `partials/footer.hbs` file. If you have some experience with HTML, it'll be no problem. When you open the file, you'll see that it's a plain HTML template with some special Ghost-specific helpers which are self-explanatory (e.g. `{{@site.title}}` for site title, `{{navigation type="secondary"}}` for secondary navigation etc) More info here: https://ghost.org/docs/themes/
