### ISSUE TITLE
Issue with portal button scroll animation

### ISSUE THREAD

**Issue by McLamy** [TryGhost/Edition#19]
There is a problem with the scroll animation of the portal button. The button is still showing when I'm at the cover section. But actually it should appear when scrolling a bit down. Got rid of this issue by putting an "!important" behind the opacity in the portal.css

**Comment by minimaluminium** [comment]
Hey @McLamy, thanks for that! Fixed in https://github.com/TryGhost/Edition/commit/5811e8709a5dcbcdc05a5260da62c0d0c195b04f
