### ISSUE TITLE
Publication Cover not displaying

### ISSUE THREAD

**Issue by alliriz8** [TryGhost/Edition#20]
The publication cover image was showing up on my Edition site but now it doesn't. It's a .png file which it says it supports. Any advice?

**Comment by minimaluminium** [comment]
Hey 👋 . Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

When you ask for support, including your site URL or any extra information like screenshots would help getting better answers.

Thanks!
