### ISSUE TITLE
Feature request: feature first image of none specificied

### ISSUE THREAD

**Issue by tedserbinski** [TryGhost/Edition#22]
Hi! I’m just digging into Ghost theme dev. Will send future pull requests :-)

For this theme is there a way to use the first image in a post as the “featured” image when listing all posts?

I often have an image in a post but don’t want the image to be featured because I need specific caption with the image. 

Thanks!

**Comment by minimaluminium** [comment]
Hey @tedserbinski,

Perfect timing 🙂

We added alt/caption support to feature image in [Ghost 4.9.0](https://github.com/TryGhost/Ghost/releases/tag/v4.9.0), and Edition was updated to support this feature in https://github.com/TryGhost/Edition/commit/59624e8a4baed5a31f8a49459880b03dbf35ea1b as well.

Update your Ghost and Edition theme, and you'll have this feature out of the box.

**Comment by tedserbinski** [comment]
Gotcha ok that works well. I wish there was a way to make an existing image featured -- otherwise have to download image, reupload -- kind of a pain.
