### ISSUE TITLE
Form attribute is gone in cover.hbs when uploading theme

### ISSUE THREAD

**Issue by McLamy** [TryGhost/Edition#23]
I ran into a strange bug. The form attribute is gone when uploading the theme. Therefore the classes "form-wrapper" and "cover-form" are missing as well so it leads to a strange looking submit button - see screenshot.

If I put another form element above the original form the new form is gone and the original looks okay again.

Running Ghost 4.9.4 in dev mode

![Bildschirmfoto 2021-07-20 um 13 33 39](https://user-images.githubusercontent.com/44198876/126317163-66ed9ef9-d331-4aaa-92a3-76107c4931f4.png)

**Comment by minimaluminium** [comment]
Hey @McLamy, do you have any live demo where we can take a look at? By missing classes, did you mean that the elements are missing from the DOM?

Also might be worth checking if there's any custom CSS or JS injection which might be overriding the elements.

**Comment by minimaluminium** [comment]
Closing the issue due to inactivity. You can always reopen it if the issue still persists.
