### ISSUE TITLE
Dark Mode? Only thing holding this theme back...

### ISSUE THREAD

**Issue by softwarememes** [TryGhost/Edition#24]
Hi,

I've just created a website with this theme - wanted to see if it would be possible to get Dark Mode going for it?

I can help develop it with some guidance (happy to do the PR).

Let me know what you all think!

Cheers,
software_memes

**Comment by minimaluminium** [comment]
Hey there, we're not planning to add dark mode to Edition. You're welcome to add the feature on your own customized Edition theme 🙂.

I assume you already know this, but just FYI, [Dawn](https://github.com/TryGhost/Dawn) theme has built-in dark mode which you can use as a reference if you want to.
