### ISSUE TITLE
Add dynamic social media

### ISSUE THREAD

**Issue by irux** [TryGhost/Edition#28]
Hello, I would like to add social media to the page. Twitter and Facebook are not enough.

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
