### ISSUE TITLE
Disqus embed issue

### ISSUE THREAD

**Issue by KazaiMazai** [TryGhost/Edition#31]
I'm facing an issue with embedding disqus comments in Edition theme.

When iserted in comments section the exact same code works as expected in other themes, for eg. Casper. 

```
{{#if post.access}}
  <div class="comment container small">
      <div id="disqus_thread"></div>
      <script>
          var disqus_config = function () {
              this.page.url = "{{url absolute="true"}}";
              this.page.identifier = "ghost-{{comment_id}}"
          };
          (function() {
          var d = document, s = d.createElement('script');
          s.src = 'https://EXAMPLE.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
      </script>
  </div>
{{/if}}

```

On Edition it embeds Disqus comments sections as expected, but doesn't fetch the comments for the page, that were posted before.

Comment can be posted successfully, however posted comment starts to show up on all the post pages.

It looks like `page.url ` or `page.identifier` for some reason works incorrectly.

Tested on ghost 4.27.1

**Comment by KazaiMazai** [comment]
Ok, I've spotted the issue. 

`comment-id` is always empty.

It looks like comments is not used in the post context correctly on upper levels. So the solution could be to force post context by wrapping into `{{#post}} ... {{/post}}`

Here is the fix:

```
{{#if post.access}}
    <div class="comment container small">
    {{#post}}
            <div id="disqus_thread"></div>
            <script>
                var disqus_config = function () {
                    this.page.url = "{{url absolute="true"}}";
                    this.page.identifier = "ghost-{{comment_id}}"
                };
                (function() {
                var d = document, s = d.createElement('script');
                s.src = 'https://EXAMPLE.disqus.com/embed.js';
                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
                })();
            </script>
    {{/post}}
    </div>
{{/if}}

```

**Comment by minimaluminium** [comment]
Hey @KazaiMazai, nice find! You're right, fixed in https://github.com/TryGhost/Edition/commit/8fea3d8d955ea8aa2a75fa1ecda14ca733efe992, thank you!
