### ISSUE TITLE
Dark Mode on Theme?

### ISSUE THREAD

**Issue by ohelabs** [TryGhost/Edition#33]
Absolutely Love this theme and was curious if there was any thought about having a dark mode option? I have seen it on a few other themes and it seems like a useful feature especially when some content and designs lend themselves to darker backgrounds.

Thanks!

**Comment by minimaluminium** [comment]
Hey @ohelabs, no dark mode plan at the moment. [Dawn](https://github.com/TryGhost/Dawn) is the closest theme to Edition and supports dark mode if you're interested :)

**Comment by minimaluminium** [comment]
You can also post it on [Ideas](https://forum.ghost.org/c/ideas/5) on our forum if you want to make it a feature request.

**Comment by Radamant24** [comment]
Hi @minimaluminium , Love this theme, but I don't think I'll start using it because of the lack of a dark/light mode toggle.
I checked Dawn but it seems the toggle is positioned at the bottom of the page, very counterintuitive at least for me.
I would appreciate the change!
