### ISSUE TITLE
Authors page feed layout switcher doesn't exists

### ISSUE THREAD

**Issue by odolbin-altexsoft** [TryGhost/Edition#9]
Hello!

There is an error in authors ![Screenshot from 2021-04-01 16-37-12](https://user-images.githubusercontent.com/64598500/113302623-f0912e80-9308-11eb-9213-23e0125af412.png)

Caused by non-existing feed layout switcher ![Screenshot from 2021-04-01 16-39-08](https://user-images.githubusercontent.com/64598500/113302604-ebcc7a80-9308-11eb-8977-27be1f848fc7.png)

**Comment by akabuda050** [comment]
The same issue for **tags** too
